### ISSUE TITLE
Feature suggestion: disable for some 'special' buffers

### ISSUE THREAD

**Issue by naartjie** [jonspalding/lisp-paredit#20]
Would it be possible to disable `lisp-paredit` for certain buffers only?

I am using it with proto-repl, and because that uses Clojure, it gets pretty crazy when paredit picks up errors in the REPL. Would it be out of scope to do a config file with something like:

```
  "ignore": ["Clojure REPL"]
```

<img width="724" alt="screen shot 2016-06-04 at 12 49 07" src="https://cloud.githubusercontent.com/assets/514563/15801688/7690236c-2a9d-11e6-8d87-8a6d1d022380.png">

**Comment by naartjie** [comment]
For the time being, I've _tamed_ the red down a bit in my `styles.less`

``` less
.lisp-paredit-status.error {
  background-color: rgba(200, 0, 200, 0.5);
}
atom-text-editor::shadow .lisp-syntax-error .region {
  background-color: rgba(80, 0, 80, 0.8) !important;
}
```

**Comment by jasongilman** [comment]
Proto REPL now uses a class for the REPL with `proto-repl-repl`. Using the previous example I can disable it completely using:

``` LESS
.proto-repl-repl::shadow .lisp-syntax-error .region {
  background-color: rgba(0, 0, 0, 0) !important;
}
```
